<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_ADDRESS_SUBDISTRICT</name>
   <tag></tag>
   <elementGuidId>18e3748d-4382-4b88-8df1-f84948283d46</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ADDRESS_SUBDISTRICT</value>
   </webElementProperties>
</WebElementEntity>
